### ISSUE TITLE
ES6 import error

### ISSUE THREAD

**Issue by xgqfrms** [webpack/loader-runner#38]
# ES6 import error

```js
// error
import { runLoaders } from "loader-runner";

```

![image](https://user-images.githubusercontent.com/7291672/82921621-2a87fa80-9fab-11ea-961e-a6dd1c849042.png)

```js
// OK
const { runLoaders } = require(`loader-runner`);

```

![image](https://user-images.githubusercontent.com/7291672/82921945-92d6dc00-9fab-11ea-8846-0038856b5531.png)

**Comment by Randy808** [comment]
There's not a lot of information to go off of in your issue. If you're implying `import { runLoaders } from "loader-runner";` doesn't work, I've tried it and wasn't able to reproduce your error. This may be a problem related to your environment rather than the codebase itself. If that makes sense then I'd suggest closing this issue and opening a StackOverflow question instead. If you still believe it's a problem with the code base, posting the entire error returned from you first screenshot (as text and not a picture) and the contents of your index.js file would help in debugging your issue.
